server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/spotifydb1
  application:
    name: user-song-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true


