#server.port=8085
#spring.datasource.url=jdbc:mysql://localhost:3306/userdb
#spring.datasource.username=root
#spring.datasource.password=Sahasiem7#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb?createDatabaseIfNotExist=true
    username: root
    password: Sahasiem7#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: auth-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true